<?php

function controlm_execute_request_menu () {
	$items = array();
	$items['controlm/execute_request'] = array(
		'title' => 'Execute Jobs on Confirm',
		'page callback' => 'controlm_execute_request_page',
		'access arguments' => array('access controlm content'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['ajax/controlm/execute_request/list_jobs'] = array(
		'page callback' => 'controlm_execute_request_list_jobs_get_ajax',
		'delivery callback' => 'controlm_execute_request_list_jobs_ajax_callback',
		'access arguments' => array('access controlm content'),
		'type' => MENU_CALLBACK,
	);
	$items['ajax/controlm/execute_request/ctmwhy'] = array(
		'page callback' => 'controlm_execute_request_ctmwhy_get_ajax',
		'delivery callback' => 'controlm_execute_request_ctmwhy_ajax_callback',
		'access arguments' => array('access controlm content'),
		'type' => MENU_CALLBACK,
	);
	$items['ajax/controlm/execute_request/freejob'] = array(
		'page callback' => 'controlm_execute_request_freejob_get_ajax',
		'delivery callback' => 'controlm_execute_request_freejob_ajax_callback',
		'access arguments' => array('access controlm content'),
		'type' => MENU_CALLBACK,
	);
	$items['ajax/controlm/execute_request/confirmjob'] = array(
		'page callback' => 'controlm_execute_request_confirmjob_get_ajax',
		'delivery callback' => 'controlm_execute_request_confirmjob_ajax_callback',
		'access arguments' => array('access controlm content'),
		'type' => MENU_CALLBACK,
	);
	$items['ajax/controlm/execute_request/pleasewait'] = array(
		'page callback' => 'controlm_execute_request_pleasewait_get_ajax',
		'delivery callback' => 'controlm_execute_request_pleasewait_ajax_callback',
		'access arguments' => array('access controlm content'),
		'type' => MENU_CALLBACK,
	);
	return $items;
}
function controlm_execute_request_page() {
	if(user_is_anonymous()) {
		return array('#markup' => '<p>You must log in to use this function.</p>');
	}

	drupal_add_library('system', 'drupal.ajax');

	$markup = "";

	$markup .= <<<EOM
<code><div id="ajax-target-command-status"></div></code>
<div id="ajax-target-job-list">Please wait one moment...</div>
<script>
	function controlm_execute_request_list_jobs_ajax_load() { 
		jQuery("#ajax-target-job-list").load("/ajax/controlm/execute_request/pleasewait"); 
		jQuery("#ajax-target-job-list").load("/ajax/controlm/execute_request/list_jobs"); 
	}
	function controlm_execute_request_ctmwhy_ajax_load(jobname,orderid) { 
		jQuery("#ajax-target-command-status").load("/ajax/controlm/execute_request/ctmwhy/" + jobname + "/" + orderid); 
	}
	function controlm_execute_request_freejob_ajax_load(jobname,orderid) { 
		jQuery("#ajax-target-command-status").load("/ajax/controlm/execute_request/freejob/" + jobname + "/" + orderid); 
	}
	function controlm_execute_request_confirmjob_ajax_load(jobname,orderid) { 
		jQuery("#ajax-target-command-status").load("/ajax/controlm/execute_request/confirmjob/" + jobname + "/" + orderid); 
	}
	function scrollToTop() { jQuery("html, body").animate({ scrollTop: 0 }, "fast"); }
	jQuery(document).ready(function($){controlm_execute_request_list_jobs_ajax_load();});
</script>
EOM;

	return(array('#markup' => t($markup)));
}
function controlm_execute_request_list_jobs_get_ajax() {
	global $user;
	$return = "<hr /><a href='#' onclick='controlm_execute_request_list_jobs_ajax_load();'>Reload Job List</a><br />";

	//Get list of assignment groups the user belongs to
	$tax_array = taxonomy_get_vocabularies();
	foreach($tax_array as $tax) {
		$taxonomies[$tax->machine_name] = $tax->vid;
	}
	$query = new EntityFieldQuery;
	$tax_result = $query->entityCondition('entity_type', 'taxonomy_term')
		->fieldCondition('field_group_members','value',$user->name)
		->propertyCondition('vid', $taxonomies['service_center_groups'])
		->execute();
	if(count($tax_result) == 0) {
		return "You are not a member of any Service Center groups.";
	}
	foreach($tax_result['taxonomy_term'] as $term) {
		$groups[$term->tid] = taxonomy_term_load($term->tid)->name;
	}
//	$return .= "<pre>".print_r($groups,TRUE)."</pre>";

	//Get list of all jobs assigned to user's groups
	foreach($groups as $tid => $groupname) {
		$query = new EntityFieldQuery();
		$query->entityCondition('entity_type','node');
		$query->propertyCondition('type','job_document');
		$query->propertyCondition('status', 1);
		$query->fieldCondition('field_service_center_group', 'tid', $tid, '=');
		$jd_result = $query->execute();
		if(isset($jd_result['node']) && is_array($jd_result['node'])) {
			foreach($jd_result['node'] as $jobdoc) {
				$title = strtolower(node_load($jobdoc->nid,$jobdoc->vid)->title);
				$jobdocs[$title] = node_load($jobdoc->nid,$jobdoc->vid);
				$userjobs[$groupname][$jobdoc->nid] = $title;
			}
		}
	}
//	$return .= "<pre>".print_r($jobdocs,TRUE)."</pre>";

	//Query DB for jobs in Wait User status
	db_set_active('bip');
	foreach($userjobs as $groupname => $groupjobs) {
		$query = db_select('cm_job_status','cjs');
		$query->fields('cjs');
		$query->condition('cmjs_job_name',$groupjobs,'IN');
		$query->condition('cmjs_status','Wait User','=');
		$query->orderBy('cmjs_job_name');
		$result = $query->execute();
		while($record = $result->fetchAssoc()) {
			$jobname = strtolower($record['CMJS_JOB_NAME']);
			$waitjobs[$groupname][$jobname] = array('status' => $record, 'jobdoc' => $jobdocs[$jobname]);
		}
	}	
	db_set_active();
//	$return .= "<pre>".print_r($waitjobs,TRUE)."</pre>";

	//Set up render array
	foreach($waitjobs as $groupname => $jobs) {
		$return .= "<h3>".$groupname."</h3>";
		$table = array(
			'#theme' => 'table',
			'#header' => array(t('Job Name'),t('Node'),t('Order Date'),t('Status'),t('State'),t('Command Line'),t('Doc'),''),
			'#rows' => array(),
		);
		foreach($jobs as $jobname => $jobprop) {
			$table['#rows'][] = array(
				t($jobprop['status']['CMJS_JOB_NAME']),
				t($jobprop['status']['CMJS_NODE_ID']),
				t($jobprop['status']['CMJS_ODATE']),
				t($jobprop['status']['CMJS_STATUS']),
				t($jobprop['status']['CMJS_STATE']),
				array('data' => t($jobprop['jobdoc']->field_command_line['und'][0]['value']),'style' => 'word-break:break-all;'),
				t("<a href='/".drupal_get_path_alias('node/'.$jobprop['jobdoc']->nid)."'>Doc</a>"),
				t('<a href="#" onclick="controlm_execute_request_ctmwhy_ajax_load(\''.$jobprop['status']['CMJS_JOB_NAME'].'\',\''.$jobprop['status']['CMJS_ORDER_ID'].'\');scrollToTop();">Why</a>'),
			);
		}
		$return .= theme('table',$table);
		$return .= "<br />";
	}
	
	return $return;
}
function controlm_execute_request_list_jobs_ajax_callback($page_callback_result) {
	echo($page_callback_result);
}

function controlm_execute_request_ctmwhy_get_ajax($jobname = '',$orderid = '') {
	if($orderid == '') return;
	$return = $jobname."<br />";

	$hostname = variable_get('controlm_hostname', '');
	$username = variable_get('controlm_username', '');
	$identity = variable_get('controlm_identity_file', '');
	$known_hosts = variable_get('controlm_known_hosts_file', '');

	$cmd = 'ssh -i '.$identity.' -o UserKnownHostsFile='.$known_hosts.' '.$username.'@'.$hostname.' "ctmwhy '.$orderid.'"';
	exec($cmd,$output,$rc);
//	$return .= "<pre>".print_r($output,TRUE)."</pre>";
	if($rc !== 0) {
		drupal_set_message('Command returned error '.$rc.': '.$cmd,'error');
		dsm($output);
		return;
	}

	$return .= implode("<br />",$output)."<br />";
	$return .= t('<a href="#" onclick="controlm_execute_request_ctmwhy_ajax_load(\''.$jobname.'\',\''.$orderid.'\');scrollToTop();">Reload Why</a><br />');
	if(in_array('Job is waiting for confirmation.',$output)) {
		$return .= t('<a href="#" onclick="controlm_execute_request_confirmjob_ajax_load(\''.$jobname.'\',\''.$orderid.'\');scrollToTop();">Confirm Job</a><br />');
	}
	if(in_array("Job is held.", $output)) {
		$return .= t('<a href="#" onclick="controlm_execute_request_freejob_ajax_load(\''.$jobname.'\',\''.$orderid.'\');scrollToTop();">Free Job</a>');
	}

	return $return;
}
function controlm_execute_request_ctmwhy_ajax_callback($page_callback_result) {
        echo($page_callback_result);
}

function controlm_execute_request_confirmjob_get_ajax($jobname = '',$orderid = '') {
	if($orderid == '') return;
	$return = "";

	$hostname = variable_get('controlm_hostname', '');
	$username = variable_get('controlm_username', '');
	$identity = variable_get('controlm_identity_file', '');
	$known_hosts = variable_get('controlm_known_hosts_file', '');

	$cmd = 'ssh -i '.$identity.' -o UserKnownHostsFile='.$known_hosts.' '.$username.'@'.$hostname.' "ctmpsm -UPDATEAJF '.$orderid.' CONFIRM"';
	exec($cmd,$output,$rc);
//	$return .= "<pre>".print_r($output,TRUE)."</pre>";
	if($rc !== 0) {
		drupal_set_message('Command returned error '.$rc.': '.$cmd,'error');
		dsm($output);
		return;
	}

	$return .= implode("<br />",$output)."<br />";
	$return .= t('<a href="#" onclick="controlm_execute_request_ctmwhy_ajax_load(\''.$jobname.'\',\''.$orderid.'\');scrollToTop();">Why</a><br />');

	return $return;
}
function controlm_execute_request_confirmjob_ajax_callback($page_callback_result) {
        echo($page_callback_result);
}

function controlm_execute_request_freejob_get_ajax($jobname = '',$orderid = '') {
	if($orderid == '') return;
	$return = "";

	$hostname = variable_get('controlm_hostname', '');
	$username = variable_get('controlm_username', '');
	$identity = variable_get('controlm_identity_file', '');
	$known_hosts = variable_get('controlm_known_hosts_file', '');

	$cmd = 'ssh -i '.$identity.' -o UserKnownHostsFile='.$known_hosts.' '.$username.'@'.$hostname.' "ctmpsm -UPDATEAJF '.$orderid.' FREE"';
	exec($cmd,$output,$rc);
//	$return .= "<pre>".print_r($output,TRUE)."</pre>";
	if($rc !== 0) {
		drupal_set_message('Command returned error '.$rc.': '.$cmd,'error');
		dsm($output);
		return;
	}

	$return .= implode("<br />",$output)."<br />";
	$return .= t('<a href="#" onclick="controlm_execute_request_ctmwhy_ajax_load(\''.$jobname.'\',\''.$orderid.'\');scrollToTop();">Why</a><br />');

	return $return;
}
function controlm_execute_request_freejob_ajax_callback($page_callback_result) {
        echo($page_callback_result);
}

function controlm_execute_request_pleasewait_get_ajax() {
	$return = "<hr />Please wait one moment...<br /><img src='".file_create_url('public://preloader.gif')."' width='50px' />";

	return $return;
}
function controlm_execute_request_pleasewait_ajax_callback($page_callback_result) {
        echo($page_callback_result);
}
