<?php

function controlm_wsdl_client_menu () {
	$items = array();
	$items['admin/config/services/controlm_wsdl_client'] = array(
		'title' => 'Control-M WSDL Client',
		'description' => 'Configuration for Control-M Web Service',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('controlm_wsdl_client_form'),
		'access arguments' => array('access administration pages'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['controlm'] = array(
		'title' => 'Control-M',
		'page callback' => 'controlm_description',
		'access callback' => TRUE,
		'expanded' => TRUE,
	);
	return $items;
}
function controlm_description() {
  return array('#markup' => '<p>' . t('Place Holder') . '</p>');
}
function controlm_wsdl_client_form ($form, &$form_state) {
	$form['controlm_wsdl_client_url'] = array(
		'#type' => 'textfield',
		'#title' => t('URL of Control-M web service'),
		'#default_value' => variable_get('controlm_wsdl_client_url', ''),
		'#size' => 255,
		'#maxlength' => 255,
		'#description' => t('The URL to the Control-M Web Service which provides the path to the extract file.'),
		'#required' => TRUE,
	);
	return system_settings_form($form);
}

