<?php

function controlm_running_long_menu () {
	$items = array();
	$items['controlm/running_long'] = array(
		'title' => 'Jobs Running Long',
		'page callback' => 'controlm_running_long_page',
		'access arguments' => array('access controlm content'),
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}

function controlm_running_long_page() {
	ini_set('memory_limit','1G');
	ini_set('max_execution_time',0);

	$refresh = array(
		'#tag' => 'meta',
		'#attributes' => array(
			'name' => 'refresh',
			'http-equiv' => 'REFRESH',
			'content' => '30',
		),
	);
	drupal_add_html_head($refresh, 'refresh');

	$return = "";

	//Set up render array
	$header = array(
		array('data' => 'Percent Above Average',	'field' => 'diff_pct',	'sort' => 'asc'),
		array('data' => 'Job Name',	'field' => 'cmja_job_name',	'sort' => 'asc'),
		array('data' => 'Node',		'field' => 'cmja_node_id',	'sort' => 'asc'),
		array('data' => 'Start Time',	'field' => 'cmjs_start_time',	'sort' => 'asc'),
		array('data' => 'Run Time',	'field' => 'run_time',		'sort' => 'asc'),
		array('data' => 'Average',	'field' => 'avg',		'sort' => 'asc'),
		array('data' => 'Difference',	'field' => 'diff',		'sort' => 'asc'),
		array('data' => 'Min',		'field' => 'min',		'sort' => 'asc'),
		array('data' => 'Max',		'field' => 'max',		'sort' => 'asc'),
		array('data' => 'Chart'),
	);

	$query = db_select('cm_job_status','cjs');
	$query->join('cm_job_average','cja','cjs.cmjs_job_name = cja.cmja_job_name');
	$query->condition('cjs.cmjs_status','Executing','=');
	$query->where('cja.cmja_dow = DAYOFWEEK(NOW())');
	$query->where('TIME_TO_SEC(TIMEDIFF(NOW(),cjs.CMJS_START_TIME)) > cja.cmja_average');
	$query->where('(TIME_TO_SEC(TIMEDIFF(NOW(),cjs.CMJS_START_TIME)) - cja.cmja_average) / cja.cmja_average > 0.1');
	$query->where('SUBSTRING(cmja_job_name,1,1) COLLATE utf8_bin = UPPER(SUBSTRING(cmja_job_name,1,1))');
	$query->addExpression('TIMEDIFF(NOW(),cjs.CMJS_START_TIME)','run_time');
	$query->addExpression('SEC_TO_TIME(cja.cmja_average)','avg');
	$query->addExpression('TIMEDIFF(TIMEDIFF(NOW(),cjs.CMJS_START_TIME),SEC_TO_TIME(cja.cmja_average))','diff');
	$query->addExpression('SEC_TO_TIME(cja.cmja_min)','min');
	$query->addExpression('SEC_TO_TIME(cja.cmja_max)','max');
	$query->addExpression('ROUND((TIME_TO_SEC(TIMEDIFF(NOW(),cjs.CMJS_START_TIME)) - cja.cmja_average) / cja.cmja_average * 100)','diff_pct');
	$query->fields('cjs',array('cmjs_start_time'));
	$query->fields('cja',array('cmja_job_name','cmja_node_id'));
//	dsm((string) $query);
//	dsm($query->arguments());
	$num_rows = $query->countQuery()->execute()->fetchField();
	if($num_rows = 0) {
		return("No long-running jobs found at this time.");
	}
	$result = $query->extend('PagerDefault')->extend('TableSort')->limit(10)->orderByHeader($header)->execute();
	foreach($result as $row) {
//		$return .= "<pre>".print_r($row,TRUE)."</pre>";
		$rows[] = array(
			t($row->diff_pct.'%'),
			t('<a href="/jobdoc/'.$row->cmja_job_name.'" target="_blank">'.$row->cmja_job_name.'</a>'),
			t($row->cmja_node_id),
			t($row->cmjs_start_time),
			t($row->run_time),
			t($row->avg),
			t($row->diff),
			t($row->min),
			t($row->max),
			t('<a href="/job-runtime-chart?job_name='.$row->cmja_job_name.'&node='.$row->cmja_node_id.'" target="_blank">Chart</a>'),
		);
	}

	$return .= theme('table',array('header' => $header,'rows' => $rows ));
	$return .= theme('pager');
	
	return($return);
}

