<?php

function service_manager_base_permission() {
	return array(
		'access service_manager content' => array( 'title' => t('Access content for the Service Manager module'), ),
		'access service_manager administration' => array( 'title' => t('Administer the Service Manager Module'), ),
		'access service_manager data feeds' => array( 'title' => t('Access data feeds for the Service Manager module'), ),
	);
}

function service_manager_base_menu () {
	$items['admin/config/services/service_manager'] = array(
		'title' => 'Service Manager',
		'description' => 'Configuration for Service Manager',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('service_manager_base_config_form'),
		'access arguments' => array('access service_manager administration'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['service_manager'] = array(
		'title' => 'Service Manager',
		'page callback' => 'service_manager_base_description',
		'access arguments' => array('access service_manager content'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['admin/config/services/service_manager/default'] = array(
                'type' => MENU_DEFAULT_LOCAL_TASK,
                'title' => 'Service Manager',
                'weight' => 1,
        );
	return $items;
}

function service_manager_base_config_form ($form, &$form_state) {
        $form['service_manager_config_wsdl_client_url'] = array(
                '#type' => 'textfield',
                '#title' => t('Configuration Management URL'),
                '#default_value' => variable_get('service_manager_config_wsdl_client_url', ''),
                '#size' => 255,
                '#maxlength' => 255,
                '#description' => t('The URL to the Service Manager Web Service for Configuration Management.'),
                '#required' => TRUE,
        );
        $form['service_manager_incident_wsdl_client_url'] = array(
                '#type' => 'textfield',
                '#title' => t('Incident Management URL'),
                '#default_value' => variable_get('service_manager_incident_wsdl_client_url', ''),
                '#size' => 255,
                '#maxlength' => 255,
                '#description' => t('The URL to the Service Manager Web Service for Incident Management.'),
                '#required' => TRUE,
        );
        $form['service_manager_assignment_wsdl_client_url'] = array(
                '#type' => 'textfield',
                '#title' => t('Assignment Management URL'),
                '#default_value' => variable_get('service_manager_assignment_wsdl_client_url', ''),
                '#size' => 255,
                '#maxlength' => 255,
                '#description' => t('The URL to the Service Manager Web Service for Assignment Management.'),
                '#required' => TRUE,
        );
        $form['service_manager_username'] = array(
                '#type' => 'textfield',
                '#title' => t('Service Manager User Name'),
                '#default_value' => variable_get('service_manager_username', ''),
                '#size' => 255,
                '#maxlength' => 255,
                '#required' => TRUE,
        );
        $form['service_manager_password'] = array(
                '#type' => 'textfield',
                '#title' => t('Service Manager Password'),
                '#default_value' => variable_get('service_manager_password', ''),
                '#size' => 255,
                '#maxlength' => 255,
                '#description' => t('The password for the Service Manager User Name above.'),
                '#required' => TRUE,
        );
        return system_settings_form($form);
}

function service_manager_base_description() {
	return array('#markup' => '<p>' . t('Place Holder') . '</p>');
}

