<?php

function controlm_base_menu () {
	$items['controlm'] = array(
		'title' => 'Control-M',
		'page callback' => 'controlm_description',
		'access arguments' => array('access controlm content'),
		//'expanded' => TRUE,
	);
	$items['admin/config/services/controlm'] = array(
                'title' => 'Control-M',
                'description' => 'Configuration for Control-M Module',
                'page callback' => 'drupal_get_form',
                'page arguments' => array('controlm_wsdl_client_form'),
                'access arguments' => array('access controlm administration'),
                'type' => MENU_NORMAL_ITEM,
        );
	$items['admin/config/services/controlm/default'] = array(
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'title' => 'WSDL Client',
		'weight' => 1,
	);
	return $items;
}

function controlm_wsdl_client_form ($form, &$form_state) {
        $form['controlm_wsdl_client_url'] = array(
                '#type' => 'textfield',
                '#title' => t('URL of Control-M web service'),
                '#default_value' => variable_get('controlm_wsdl_client_url', ''),
                '#size' => 255,
                '#maxlength' => 255,
                '#description' => t('The URL to the Control-M Web Service which provides the path to the extract file.'),
                '#required' => TRUE,
        );
        $form['controlm_newday'] = array(
                '#type' => 'textfield',
                '#title' => t('New Day Time'),
                '#default_value' => variable_get('controlm_newday', ''),
                '#size' => 20,
                '#maxlength' => 20,
                '#description' => t('The time of the Control-M new day.'),
                '#required' => TRUE,
        );
        $form['controlm_hostname'] = array(
                '#type' => 'textfield',
                '#title' => t('Control-M Host Name'),
                '#default_value' => variable_get('controlm_hostname', ''),
                '#size' => 64,
                '#maxlength' => 255,
                '#description' => t('The Host Name or IP address of Control-M server'),
                '#required' => TRUE,
        );
        $form['controlm_identity_file'] = array(
                '#type' => 'textfield',
                '#title' => t('Identity File'),
                '#default_value' => variable_get('controlm_identity_file', ''),
                '#size' => 64,
                '#maxlength' => 255,
                '#description' => t('The SSH identity file that will be used to access the Control-M server'),
                '#required' => TRUE,
        );
        $form['controlm_known_hosts_file'] = array(
                '#type' => 'textfield',
                '#title' => t('Known Hosts File'),
                '#default_value' => variable_get('controlm_known_hosts_file', ''),
                '#size' => 64,
                '#maxlength' => 255,
                '#description' => t('The SSH known hosts file that will be used to access the Control-M server'),
                '#required' => TRUE,
        );
        $form['controlm_username'] = array(
                '#type' => 'textfield',
                '#title' => t('Control-M User Name'),
                '#default_value' => variable_get('controlm_username', ''),
                '#size' => 64,
                '#maxlength' => 255,
                '#description' => t('The username that will be used to access the Control-M server'),
                '#required' => TRUE,
        );
        $form['controlm_em_username'] = array(
                '#type' => 'textfield',
                '#title' => t('Control-M EM User Name'),
                '#default_value' => variable_get('controlm_em_username', ''),
                '#size' => 64,
                '#maxlength' => 255,
                '#description' => t('The username that will be used to access CTMEM on the Control-M server'),
                '#required' => TRUE,
        );
        $form['controlm_em_db_type'] = array(
                '#type' => 'select',
                '#title' => t('Control-M EM DB Type'),
                '#default_value' => variable_get('controlm_em_db_type', array('standard' => 'standard')),
		'#options' => array('standard' => 'standard', 'oci8' => 'oci8'),
                '#description' => t('The DB driver for the CTMEM database'),
                '#required' => TRUE,
        );
        return system_settings_form($form);
}

function controlm_description() {
  return array('#markup' => '<p>' . t('Place Holder') . '</p>');
}

function controlm_base_permission() {
	return array(
		'access controlm content' => array( 'title' => t('Access content for the Control-M module'), ),
		'access controlm administration' => array( 'title' => t('Administer the Control-M Module'), ),
		'access controlm data feeds' => array( 'title' => t('Access data feeds for the Control-M module'), ),
	);
}

