<?php

/*****************************************************************/
/* Function to generate the correlation coefficient of 2 arrays. */
/* Arrays should be of the same length.                          */
/*****************************************************************/
function corrCoef($arrayX,$arrayY){
    global $debug;

    $n = sizeof($arrayX);
        if($n == 0) return 0;
    $sumX=0;
    $sumX2=0;
    $sumY=0;
    $sumY2=0;
    $sumXY=0;
    $i=0;
    for($i=0;$i<$n;$i++){
        $sumX += $arrayX[$i];
        $sumX2+= pow($arrayX[$i],2);
        $sumXY += $arrayX[$i]*$arrayY[$i];
        $sumY += $arrayY[$i];
        $sumY2+= pow($arrayY[$i],2);
    }
    if(isset($debug) && $debug == "true"){
#        print "sumX=$sumX\n";
#        print "sumX2=$sumX2\n";
#        print "sumY=$sumY\n";
#        print "sumY2=$sumY2\n";
#        print "sumXY=$sumXY\n";
    }

    if(sqrt(abs(($sumX2-((1/$n)*pow($sumX,2)))*($sumY2-((1/$n)*pow($sumY,2))))) != 0){
        $corrCoef=($sumXY-((1/$n)*$sumX*$sumY))/sqrt(abs(($sumX2-((1/$n)*pow($sumX,2)))*($sumY2-((1/$n)*pow($sumY,2)))));
    }else{
        $corrCoef=0;
    }
    //print "Correlation Coefficient=$corrCoef";
    return $corrCoef;
}

