<?php

function controlm_view_job_list_menu () {
	$items = array();
	$items['controlm/view_job_list'] = array(
		'title' => 'View Job List',
		'page callback' => 'controlm_view_job_list_execute',
		'access arguments' => array('access controlm content'),
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}
function controlm_view_job_list_execute() {
	$arr = drupal_get_form('controlm_view_job_list_form');
	$markup = drupal_render($arr);
	return array('#markup' => '<p>' . t($markup) . '</p>');
}
function controlm_view_job_list_form ($form, &$form_state) {
	$form = array();
	$form['group1'] = array(
		'#type' => 'fieldset',
		'#title' => t('Search Parameters'),
		'#collapsible' => TRUE,
		'#collapsed' => TRUE,
	);
	$form['group1']['cmji_jobname'] = array(
		'#title' => t('Job Name'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_nodeid'] = array(
		'#title' => t('Node'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_description'] = array(
		'#title' => t('Description'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_cmdline'] = array(
		'#title' => t('Command Line'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_owner'] = array(
		'#title' => t('Owner'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_application'] = array(
		'#title' => t('CTM Application'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_group'] = array(
		'#title' => t('CTM Group'),
		'#type' => 'textfield',
	);
	$form['group1']['cmjp_value'] = array(
		'#title' => t('Property Value'),
		'#type' => 'textfield',
	);
	$form['orderby_options'] = array(
		'#type' => 'value',
		'#value' => array(
			'cmji_jobname' => t('Job Name'),
			'cmji_nodeid' => t('Node'),
			'cmji_description' => t('Description'),
//			'cmjs_status' => t('Status'),
		),
	);
	$form['group2']['orderby'] = array(
		'#title' => t('Order results by'),
		'#type' => 'select',
		'#options' => $form['orderby_options']['#value'],
	);
	$form['group2']['submit'] = array(
		'#value' => t('Search'),
		'#type' => 'submit',
		'#submit' => array('controlm_view_job_list_form_submit'),
	);

	if(isset($form_state['storage']['results'])) {
		$form['results'] = $form_state['storage']['results'];
	}

	return $form;
}
function controlm_view_job_list_form_submit ($form, &$form_state) {

	ini_set('memory_limit','1G');
	ini_set('max_execution_time',0);

	//get all taxonomy vocabulary ID's
	$tax_array = taxonomy_get_vocabularies();
	foreach($tax_array as $tax) {
		$taxonomies[$tax->machine_name] = $tax->vid;
	}
	
	//Get images for each job status - stored as image nodes in Drupal
	db_set_active('bip');
	$result = db_select('cm_job_status','cmjs')->distinct()->fields('cmjs',array('cmjs_status'))->execute();
	db_set_active();

	while($status = $result->fetchField()) {
		$query = new EntityFieldQuery();
		$entities = $query->entityCondition('entity_type', 'node')
			->propertyCondition('type', 'image')
			->propertyCondition('title', $status)
			//->propertyCondition('status', 1)
			->range(0,1)
			->execute();
		if (!empty($entities['node'])) {
			$node = node_load(array_shift(array_keys($entities['node'])));
			$images[$status] = file_create_url($node->field_image['und'][0]['uri']);
		}
	}


	//Set up render array 
	$table = array(
		'#theme' => 'table',
		'#header' => array(t('Status'),t('Job Name'),t('Node'),t('Description'),t('Start Time'),t('Doc'),t('Info'),t('Chart')),
		'#rows' => array(),
	);

	//Query DB
	foreach($form_state['values'] as $k => $v) {
		if(!(strstr($k,'cmji_') || strstr($k,'cmjp_')) || $v == '') {
			continue;
		}
		$where[$k] = $v;
	}

	db_set_active('bip');
	$query = db_select('cm_job_info','cmji');
	$query->leftJoin('cm_job_status','cmjs','cmji.cmji_jobname = cmjs.cmjs_job_name AND cmji.cmji_nodeid = cmjs.cmjs_cpu_id');
	$query->leftJoin('cm_job_properties','cmjp','cmji.cmji_id = cmjp.cmjp_job_id');
	$query->fields('cmji',array('cmji_jobname','cmji_nodeid','cmji_description','cmji_table_id'));
	$query->fields('cmjs',array('cmjs_status','cmjs_start_time'));
	if(isset($where)) {
		foreach($where as $k => $v) {
			$query->condition($k,'%'.$v.'%','LIKE');
		}
	}
	$query->orderBy($form_state['values']['orderby']);
	$query->distinct();
	$result = $query->execute();
	db_set_active();
	
	while($record = $result->fetchAssoc()) {

		//Look up Taxonomy ID's of job name and node
		unset($job_name_tid); 
		unset($node_id_tid);
		$query = new EntityFieldQuery();
		$tax_result = $query->entityCondition('entity_type','taxonomy_term')
			->propertyCondition('name',$record['cmji_jobname'])
			->propertyCondition('vid',$taxonomies['control_m_jobs'])
			->execute();
		if(count($tax_result) !== 0) {
			$job_name_tid = array_shift($tax_result['taxonomy_term'])->tid;
		}
		$query = new EntityFieldQuery();
		$tax_result = $query->entityCondition('entity_type', 'taxonomy_term')
			->propertyCondition('name',$record['cmji_nodeid'])
			->propertyCondition('vid', $taxonomies['control_m_nodes'])
			->execute();
		if(count($tax_result) !== 0) {
			$node_id_tid = array_shift($tax_result['taxonomy_term'])->tid;
		}

		//Get status image if it exists
		if(isset($images[$record['cmjs_status']])) {
			$stat = "<img src='".$images[$record['cmjs_status']]."' title='".$record['cmjs_status']."' style='height: 24px; width: 24px;' />";
		} else {
			$stat = $record['cmjs_status'];
		}

		//Look up Job Document node
		$doc = "";
		if(isset($job_name_tid) && isset($node_id_tid)) {
			$query = new EntityFieldQuery();
			$query->entityCondition('entity_type','node');
			$query->propertyCondition('type','job_document');
			$query->propertyCondition('status', 1);
			$query->fieldCondition('field_job_name', 'tid', $job_name_tid, '=');
			$query->fieldCondition('field_node_id', 'tid', $node_id_tid, '=');
			$jd_result = $query->execute();
			if (!empty($jd_result['node'])) {
				$jobdoc_nids = array_keys($jd_result['node']);
				$doc = "<a href='/".drupal_get_path_alias('node/'.$jobdoc_nids[0])."'>Doc</a>";
			}
		}
		
/*
		if(isset($jobdocs[$record['JOB_NAME']][$record['NODE_ID']])) {
                        $doc = "<a href='/".$jobdocs[$record['JOB_NAME']][$record['NODE_ID']]."'>Doc</a>";
                } else {
                        $doc = "";
                }
*/
		$table['#rows'][] = array(
			t($stat),
			t(trim($record['cmji_jobname'])),
			t($record['cmji_nodeid']),
			t($record['cmji_description']),
			t($record['cmjs_start_time']),
			$doc,
			t('<a href="/job-information?job_name='.$record['cmji_jobname'].'" target="_blank">Info</a>'),
			t('<a href="/job-runtime-chart?job_name='.$record['cmji_jobname'].'&node='.$record['cmji_nodeid'].'" target="_blank">Chart</a>'),
		);
	}
/*
	foreach($form_state['values'] as $k => $v) {
		if(!(strstr($k,'cmji_') || strstr($k,'cmjp_')) || $v == '') {
			continue;
		}
		$where[$k] = $v;
	}
	$query = db_select('cm_job_info','cmji');
	$query->join('cm_job_status','cmjs','cmji.cmji_jobname = cmjs.cmjs_job_name AND cmji.cmji_nodeid = cmjs.cmjs_cpu_id');
	$query->fields('cmji',array('cmji_jobname','cmji_nodeid','cmji_description','cmji_table_id'));
	$query->fields('cmjs',array('cmjs_status'));
	if(isset($where)) {
		foreach($where as $k => $v) {
			$query->condition($k,'%'.$v.'%','LIKE');
		}
	}
	$query->orderBy($orderby);
	$result = $query->execute();
	//Add query results to render array
	while($row = $result->fetchAssoc()) {
		if(isset($images[$row['cmjs_status']])) {
			$stat = "<img src='".$images[$row['cmjs_status']]."' title='".$row['cmjs_status']."' style='height: 24px; width: 24px;' />";
		} else {
			$stat = $row['cmjs_status'];
		}
		if(isset($jobdocs[$row['JOB_NAME']])) {
			$doc = "<a href='/".$jobdocs[$row['JOB_NAME']]."'>Doc</a>";
		} else {
			$doc = "";
		}
		$table['#rows'][] = array(
			t($stat),
			t($row['JOB_NAME']),
			t($row['NODE_ID']),
			t($row['DESCRIPTION']),
			t($doc),
			t('<a href="/job-information?job_name='.$row['JOB_NAME'].'" target="_blank">Info</a>'),
			t('<a href="/job-runtime-chart?job_name='.$row['JOB_NAME'].'&node='.$row['cmji_nodeid'].'" target="_blank">Chart</a>'),
		);
	}
*/

	$form_state['storage']['results'] = $table;
	$form_state['rebuild'] = TRUE;

	db_set_active();
	return $table;
}

