<?php

function controlm_view_job_list_menu () {
	$items = array();
	$items['controlm/view_job_list'] = array(
		'title' => 'View Job List',
		'page callback' => 'controlm_view_job_list_execute',
		'access arguments' => array('access controlm content'),
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}
function controlm_view_job_list_execute() {
	$arr = drupal_get_form('controlm_view_job_list_form');
	$markup = drupal_render($arr);
	return array('#markup' => '<p>' . t($markup) . '</p>');
}
function controlm_view_job_list_form ($form, &$form_state) {
	$form = array();
	$form['group1'] = array(
		'#type' => 'fieldset',
		'#title' => t('Search Parameters'),
		'#collapsible' => TRUE,
		'#collapsed' => TRUE,
	);
	$form['group1']['cmji_jobname'] = array(
		'#title' => t('Job Name'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_nodeid'] = array(
		'#title' => t('Node'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_description'] = array(
		'#title' => t('Description'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_cmdline'] = array(
		'#title' => t('Command Line'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_owner'] = array(
		'#title' => t('Owner'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_weekscal'] = array(
		'#title' => t('Weekdays Calendar'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_dayscal'] = array(
		'#title' => t('Month Days Calendar'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_confcal'] = array(
		'#title' => t('ConfCal'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_application'] = array(
		'#title' => t('CTM Application'),
		'#type' => 'textfield',
	);
	$form['group1']['cmji_group'] = array(
		'#title' => t('CTM Group'),
		'#type' => 'textfield',
	);
	$form['orderby_options'] = array(
		'#type' => 'value',
		'#value' => array(
			'cmji_jobname' => t('Job Name'),
			'cmji_nodeid' => t('Node'),
			'cmji_description' => t('Description'),
			'cmjs_status' => t('Status'),
		),
	);
	$form['group2']['orderby'] = array(
		'#title' => t('Order results by'),
		'#type' => 'select',
		'#options' => $form['orderby_options']['#value'],
	);
	$form['group2']['submit'] = array(
		'#value' => t('Search'),
		'#type' => 'submit',
		'#submit' => array('controlm_view_job_list_form_submit'),
	);

	if(isset($form_state['storage']['results'])) {
		$form['results'] = $form_state['storage']['results'];
	}

	return $form;
}
function controlm_view_job_list_form_submit ($form, &$form_state) {
	db_set_active('bip');

	$result = db_select('cm_job_status','cmjs')->distinct()->fields('cmjs',array('cmjs_status'))->execute();
	while($status = $result->fetchField()) {
		db_set_active();
		$query = new EntityFieldQuery();
		$entities = $query->entityCondition('entity_type', 'node')
			->propertyCondition('type', 'image')
			->propertyCondition('title', $status)
			//->propertyCondition('status', 1)
			->range(0,1)
			->execute();
		if (!empty($entities['node'])) {
			$node = node_load(array_shift(array_keys($entities['node'])));
			$images[$status] = file_create_url($node->field_image['und'][0]['uri']);
		}
		db_set_active('bip');
	}

	$orderby = $form_state['values']['orderby'];
	foreach($form_state['values'] as $k => $v) {
		if(!(strstr($k,'cmji_') || strstr($k,'cmjp_')) || $v == '') {
			continue;
		}
		$where[$k] = $v;
	}

	$table = array(
		'#theme' => 'table',
		'#header' => array(t('Status'),t('Job Name'),t('Node'),t('Description')),
		'#rows' => array(),
	);

	$query = db_select('cm_job_info','cmji');
	$query->join('cm_job_status','cmjs','cmji.cmji_jobname = cmjs.cmjs_job_name AND cmji.cmji_nodeid = cmjs.cmjs_cpu_id');
	$query->fields('cmji',array('cmji_jobname','cmji_nodeid','cmji_description','cmji_table_id'));
	$query->fields('cmjs',array('cmjs_status'));
	if(isset($where)) {
		foreach($where as $k => $v) {
			$query->condition($k,'%'.$v.'%','LIKE');
		}
	}
	$query->orderBy($orderby);
	$result = $query->execute();

	while($row = $result->fetchAssoc()) {
		if(isset($images[$row['cmjs_status']])) {
			$stat = "<img src='".$images[$row['cmjs_status']]."' title='".$row['cmjs_status']."' style='height: 24px; width: 24px;' />";
		} else {
			$stat = $row['cmjs_status'];
		}
		$table['#rows'][] = array(
			$stat,
			//t($row['cmjs_status']),
			t($row['cmji_jobname']),
			t($row['cmji_nodeid']),
			t($row['cmji_description']),
		);
	}

	$form_state['storage']['results'] = $table;
	$form_state['rebuild'] = TRUE;

	db_set_active();
	return $table;
}

